version: '3.3'

services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - 6379:6379

  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - sqlite-db:/app
    ports:
      - 8000:8000
    command: ["pipenv", "run" ,"uvicorn","app.main:app","--host" ,"0.0.0.0", "--port", "8000"]
    depends_on:
      - redis

  celery:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - sqlite-db:/app
    command: ["pipenv","run","celery", "-A", "app.main.celery", "worker" ,"-l","INFO"]
    depends_on:
      - web

volumes:
  sqlite-db:
   external: true